### ISSUE TITLE
Thanks for this plugin !

### ISSUE THREAD

**Issue by davephillips** [korfuri/WhatTheRack#1]
Just a comment to say "Thank you!" for these excellent modules. You're right, they bring back the fun factor like when I first started using Rack. And yes, I tend to use a well-defined workflow, so every now & then it's a good idea to get out of that flow. Your modules make it easy to do that, I find them very provocative for the creative mind.

Best regards,

Dave Phillips

**Comment by korfuri** [comment]
I'm really glad you like it! Thanks for the kind words!
