### ISSUE TITLE
All the What The's Crash Rack 1.1.4

### ISSUE THREAD

**Issue by BoscoRemus** [korfuri/WhatTheRack#3]
All of the modules crash the New Rack 1.1.4..
Remove the What the rack folder and no problems..

**Comment by BoscoRemus** [comment]
Should point out on a MAC 10.14.5

**Comment by BoscoRemus** [comment]
[log.txt](https://github.com/korfuri/WhatTheRack/files/3532712/log.txt)

**Comment by BoscoRemus** [comment]
[log.txt](https://github.com/korfuri/WhatTheRack/files/3532718/log.txt)

**Comment by wiqid** [comment]
on win10 as well

is this a private rack api issue, like https://github.com/VCVRack/Rack/issues/1534?

**Comment by korfuri** [comment]
Indeed, it seems to be an ABI compatibility issue. I've released v1.1.0 at https://github.com/korfuri/WhatTheRack/releases/tag/1.1.0 which fixes it. Please test it and let me know if you still have issues - I'm going to assume this works and close this in the meantime. Thanks for the reports!

**Comment by BoscoRemus** [comment]
Thanks!!
